#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

cross_server:
  deploy_to: '/home/xu/apps/diaspora'
  user: 'xu'
  port: 33891
  repo: 'git://github.com/diaspora/diaspora.git'
  branch: 'public-permalinks'
  default_env: 'development'
servers:
  tom:
    - url: 'symposium.bayshorenetworks.com'
  backer:
    - username: 'xu'
